#!/usr/bin/env bash
# Generate a Compose fragment with N robot services for the edge topology.
# Each robot container runs its own kafka_sink or mosquitto_sink alongside
# the publisher — no central sink needed.
#
# Usage: BROKER=kafka ./gen_fleet.sh <num_robots> <output_file>
# Env:   BROKER   — kafka (default) or mqtt
#        RATE_HZ  — replay rate (default: 10)
#        MSG_TYPE — multi (default) | navsatfix | odometry | laserscan | pointcloud2
set -euo pipefail

N="${1:?usage: ./gen_fleet.sh <num_robots> <output_file>}"
OUT="${2:?usage: ./gen_fleet.sh <num_robots> <output_file>}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BROKER="${BROKER:-kafka}"
RATE_HZ="${RATE_HZ:-10}"
MSG_TYPE="${MSG_TYPE:-multi}"
# Default payload: JSON for Kafka (consumer-friendly), CDR for MQTT (smaller, avoids
# introspection issues with nested message types like NavSatFix on some builds).
if [[ "${BROKER}" == "mqtt" ]]; then
    PAYLOAD_FORMAT="${PAYLOAD_FORMAT:-cdr}"
else
    PAYLOAD_FORMAT="${PAYLOAD_FORMAT:-json}"
fi

TOPOLOGY="${TOPOLOGY:-shared}"

if [[ "${TOPOLOGY}" == "per-robot" && "${BROKER}" != "mqtt" ]]; then
    echo "ERROR: TOPOLOGY=per-robot is only supported with BROKER=mqtt" >&2
    exit 1
fi
if [[ "${TOPOLOGY}" != "shared" && "${TOPOLOGY}" != "per-robot" ]]; then
    echo "ERROR: unknown TOPOLOGY=${TOPOLOGY}; expected 'shared' or 'per-robot'" >&2
    exit 1
fi

IMAGE="ghcr.io/lrmput/ros2-kafka-dispatcher:latest"

# Optional per-robot latency log mount. Empty unless LATENCY_LOG_DIR is set in
# the environment (the run_latency_capture.sh orchestrator sets it). The
# ${LATENCY_LOG_DIR} reference stays literal so Docker Compose substitutes the
# host path at `up` time.
LATENCY_ENV=""
LATENCY_VOL=""
if [[ -n "${LATENCY_LOG_DIR:-}" ]]; then
    LATENCY_ENV=$'\n      LATENCY_LOG_DIR: "/latency"'
    LATENCY_VOL=$'\n      - ${LATENCY_LOG_DIR}:/latency'
fi

# For per-robot MQTT topology, generate per-robot mosquitto configs with the correct
# listener port. Each broker container gets its own config file in OUT_DIR.
OUT_DIR="$(dirname "${OUT}")"

cat > "${OUT}" <<'HEADER'
# Auto-generated by gen_fleet.sh — do not edit by hand.
services:
HEADER

for ((i = 1; i <= N; i++)); do
    if [[ "${TOPOLOGY}" == "per-robot" ]]; then
        PORT=$((1882 + i))
        # Generate per-robot mosquitto config with the correct listener port.
        BROKER_CONF="${OUT_DIR}/mosquitto_broker_${i}.conf"
        sed "s/^listener .*/listener ${PORT}/" "${SCRIPT_DIR}/mosquitto.conf" > "${BROKER_CONF}"
        cat >> "${OUT}" <<EOF
  broker_${i}:
    image: eclipse-mosquitto:2.0
    network_mode: host
    volumes:
      - ${BROKER_CONF}:/mosquitto/config/mosquitto.conf:ro
EOF
        cat >> "${OUT}" <<EOF
  robot_${i}:
    image: ${IMAGE}
    network_mode: host
    ipc: host
    environment:
      ROBOT_ID: "${i}"
      BAG_PATH: "/data/bag"
      RATE_HZ: "${RATE_HZ}"
      MSG_TYPE: "${MSG_TYPE}"
      SINK_KIND: "mqtt"
      BROKER_HOST: "localhost"
      BROKER_PORT: "${PORT}"
      MQTT_QOS: "1"
      PAYLOAD_FORMAT: "${PAYLOAD_FORMAT}"${LATENCY_ENV}
    volumes:
      - "\${BAG_PATH:?BAG_PATH is required}:/data/bag:ro"
      - ${SCRIPT_DIR}/edge_entrypoint.sh:/usr/local/bin/edge_entrypoint.sh:ro
      - ${SCRIPT_DIR}/robot_replay.py:/app/robot_replay.py:ro${LATENCY_VOL}
    entrypoint: ["/usr/local/bin/edge_entrypoint.sh"]
    depends_on:
      - broker_${i}
    restart: "no"
EOF
    else
        cat >> "${OUT}" <<EOF
  robot_${i}:
    image: ${IMAGE}
    network_mode: host
    ipc: host
    environment:
      ROBOT_ID: "${i}"
      BAG_PATH: "/data/bag"
      RATE_HZ: "${RATE_HZ}"
      MSG_TYPE: "${MSG_TYPE}"
      SINK_KIND: "${BROKER}"
      BROKER_HOST: "localhost"
      BROKER_PORT: "1883"
      MQTT_QOS: "1"
      PAYLOAD_FORMAT: "${PAYLOAD_FORMAT}"${LATENCY_ENV}
    volumes:
      - "\${BAG_PATH:?BAG_PATH is required}:/data/bag:ro"
      - ./edge_entrypoint.sh:/usr/local/bin/edge_entrypoint.sh:ro
      - ./robot_replay.py:/app/robot_replay.py:ro${LATENCY_VOL}
    entrypoint: ["/usr/local/bin/edge_entrypoint.sh"]
    depends_on:
      - broker
    restart: "no"
EOF
    fi
done

echo "[gen_fleet] wrote ${N} robot services (broker=${BROKER}, topology=${TOPOLOGY}, msg_type=${MSG_TYPE}, payload=${PAYLOAD_FORMAT}) → ${OUT}"
