#!/usr/bin/env bash
# Generate a Compose fragment with N robot services (edge topology).
# Each robot container runs its own kafka_sink or mosquitto_sink alongside
# the publisher — no central sink needed.
#
# Fleet routing (FLEET_ROUTING=1, default for Kafka):
#   All robots write to one shared Kafka fleet topic (ros2.fleet.<suffix>)
#   with kafka_key=robot_<id>, enabling a single ksqlDB query for all robots.
#
# Usage: BROKER=kafka ./gen_fleet.sh <num_robots> <output_file>
# Env:   BROKER        — kafka (default) | mqtt
#        RATE_HZ       — replay rate (default: 10)
#        MSG_TYPE      — multi (default) | navsatfix | odometry | laserscan | pointcloud2
#        FLEET_ROUTING — 1 (default for kafka) | 0 (per-robot topics)
set -euo pipefail

N="${1:?usage: ./gen_fleet.sh <num_robots> <output_file>}"
OUT="${2:?usage: ./gen_fleet.sh <num_robots> <output_file>}"
BROKER="${BROKER:-kafka}"
RATE_HZ="${RATE_HZ:-10}"
MSG_TYPE="${MSG_TYPE:-multi}"
if [[ "${BROKER}" == "mqtt" ]]; then
    FLEET_ROUTING="${FLEET_ROUTING:-0}"
    PAYLOAD_FORMAT="${PAYLOAD_FORMAT:-cdr}"
else
    FLEET_ROUTING="${FLEET_ROUTING:-1}"
    PAYLOAD_FORMAT="${PAYLOAD_FORMAT:-json}"
fi

IMAGE="ghcr.io/lrmput/ros2-kafka-dispatcher:latest"

# Cryptographic salts to guarantee a Perfect Hash Function across 50 partitions
# robot_1_s79  -> Partition 0
# robot_2_s106 -> Partition 1
# robot_3_s83  -> Partition 2 ... up to Partition 49
#goodformurmur2SALTS=(79 106 83 21 56 10 7 8 9 0 15 85 252 9 29 69 73 96 82 4 2 61 1 22 11 118 104 2 45 71 10 37 10 25 232 0 166 95 67 54 31 35 2 1 53 17 80 40 60 36)

SALTS=(7514 415 1170 3151 3267 3909 6919 5531 482 791 15 6821 1257 3170 1416 1179 5979 4969 3535 3223 1704 1003 6726 4094 1211 12416 7662 2248 45 4045 1984 694 1652 5238 743 3587 8131 2834 494 2739 31 3020 64 8968 2110 5287 2721 2348 172 804)

cat > "${OUT}" <<'HEADER'
# Auto-generated by gen_fleet.sh — do not edit by hand.
services:
HEADER

for ((i = 1; i <= N; i++)); do
    # Fetch the corresponding salt from our zero-indexed bash array
    SALT="${SALTS[$((i-1))]}"
    SALTED_ID="${i}_s${SALT}"

    cat >> "${OUT}" <<EOF
  robot_${i}:
    image: ${IMAGE}
    network_mode: host
    ipc: host
    environment:
      ROBOT_ID: "${SALTED_ID}"
      BAG_PATH: "/data/bag"
      RATE_HZ: "${RATE_HZ}"
      MSG_TYPE: "${MSG_TYPE}"
      SINK_KIND: "${BROKER}"
      BROKER_HOST: "127.0.0.1"
      MQTT_QOS: "1"
      PAYLOAD_FORMAT: "${PAYLOAD_FORMAT}"
      FLEET_ROUTING: "${FLEET_ROUTING}"
    volumes:
      - "\${BAG_PATH:?BAG_PATH is required}:/data/bag:ro"
      - ./edge_entrypoint.sh:/usr/local/bin/edge_entrypoint.sh:ro
      - ./robot_replay.py:/app/robot_replay.py:ro
    entrypoint: ["/usr/local/bin/edge_entrypoint.sh"]
    depends_on:
      - broker
    restart: "no"
EOF
done

echo "[gen_fleet] wrote ${N} robot services (broker=${BROKER}, msg_type=${MSG_TYPE}, fleet_routing=${FLEET_ROUTING}, payload=${PAYLOAD_FORMAT}) → ${OUT}"
