coordinatorHost: 127.0.0.1
coordinatorPort: 4000
localWorkerHost: 127.0.0.1
workerId: 4
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gnss
    physicalSourceName: robot_3_gnss
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1885
      topic: ros2/robot_3/gnss
  - logicalSourceName: odom
    physicalSourceName: robot_3_odom
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1885
      topic: ros2/robot_3/odom
  - logicalSourceName: scan
    physicalSourceName: robot_3_scan
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1885
      topic: ros2/robot_3/scan
  - logicalSourceName: points
    physicalSourceName: robot_3_points
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1885
      topic: ros2/robot_3/points
