coordinatorHost: 127.0.0.1
coordinatorPort: 4000
localWorkerHost: 127.0.0.1
workerId: 2
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gnss
    physicalSourceName: robot_1_gnss
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1883
      topic: ros2/robot_1/gnss
  - logicalSourceName: odom
    physicalSourceName: robot_1_odom
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1883
      topic: ros2/robot_1/odom
  - logicalSourceName: scan
    physicalSourceName: robot_1_scan
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1883
      topic: ros2/robot_1/scan
  - logicalSourceName: points
    physicalSourceName: robot_1_points
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1883
      topic: ros2/robot_1/points
