coordinatorHost: 127.0.0.1
coordinatorPort: 4000
localWorkerHost: 127.0.0.1
workerId: 5
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gnss
    physicalSourceName: robot_4_gnss
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1886
      topic: ros2/robot_4/gnss
  - logicalSourceName: odom
    physicalSourceName: robot_4_odom
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1886
      topic: ros2/robot_4/odom
  - logicalSourceName: scan
    physicalSourceName: robot_4_scan
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1886
      topic: ros2/robot_4/scan
  - logicalSourceName: points
    physicalSourceName: robot_4_points
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1886
      topic: ros2/robot_4/points
