coordinatorHost: 127.0.0.1
coordinatorPort: 4000
localWorkerHost: 127.0.0.1
workerId: 6
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gnss
    physicalSourceName: robot_5_gnss
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1887
      topic: ros2/robot_5/gnss
  - logicalSourceName: odom
    physicalSourceName: robot_5_odom
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1887
      topic: ros2/robot_5/odom
  - logicalSourceName: scan
    physicalSourceName: robot_5_scan
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1887
      topic: ros2/robot_5/scan
  - logicalSourceName: points
    physicalSourceName: robot_5_points
    type: MQTT_SOURCE
    configuration:
      url: 127.0.0.1:1887
      topic: ros2/robot_5/points
